language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
